language: haxe

haxe:
  - development
  - "3.2.0"
  - "3.1.3"

matrix:
  allow_failures:
    - haxe: development

addons:
  apt:
    packages:
      - php5-cli
      - mono-devel
      - mono-mcs

install:
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs

script:
  - haxe build.hxml